package com.qrcodescanner.barcodereader.qrgenerator.utils

import com.qrcodescanner.barcodereader.qrgenerator.R

object AllCountrylistMe {

    public fun getCountryList(): ArrayList<CountryModel> {
        val arrayList = ArrayList<CountryModel>()
        arrayList.add(CountryModel("English (En)", R.drawable.united_states_of_america, "en", "en-US"))
        arrayList.add(CountryModel("Afrikaans (Afrikaans)", R.drawable.south_africa, "af", "af-ZA"))
        arrayList.add(CountryModel("Albanian (shqiptar)", R.drawable.albania, "sq", "sq-AL"))
        arrayList.add(CountryModel("Amharic (አማርኛ)", R.drawable.ethiopia, "am", "am-ET"))
        arrayList.add(CountryModel("Arabic (العربية)", R.drawable.ic_saudi_arabia, "ar", "ar-SA"))
        arrayList.add(CountryModel("Armenian (հայերեն)", R.drawable.armenia, "hy", "hy-AM"))
        arrayList.add(CountryModel("Azeerbaijani (Azərbaycan)", R.drawable.azerbaijan, "az", "az-AZ"))
        arrayList.add(CountryModel("Basque (Euskara)", R.drawable.basque_country, "eu", "eu-ES"))
        arrayList.add(CountryModel("Bengali (বাংলা)", R.drawable.bangladesh, "bn", "bn-BD"))
        arrayList.add(CountryModel("Bengali (বাংলা)", R.drawable.india, "bn", "bn-IN"))
        arrayList.add(CountryModel("Bosnian (Bosanski)", R.drawable.bosnia_and_herzegovina, "bs", "bs-BA"))
        arrayList.add(CountryModel("Bulgarian (български)", R.drawable.bulgaria, "bg", "bg-BG"))
        arrayList.add(CountryModel("Burmese (ဗမာ)", R.drawable.myanmar, "my", "my-MM"))
        arrayList.add(CountryModel("Catalan (Català)", R.drawable.catalon, "ca", "ca-ES"))
        arrayList.add(CountryModel("Cebuano (Cebuano)", R.drawable.philippines, "ceb", "ceb-PHL"))
        arrayList.add(CountryModel("Chinese Simplified (中文简体)", R.drawable.china, "zh", "zh-CN"))
        arrayList.add(CountryModel("Croatian (Croatian)", R.drawable.croatia, "hr", "hr-HR"))
        arrayList.add(CountryModel("Czech (češki)", R.drawable.czech_republic, "cs", "cs-CZ"))
        arrayList.add(CountryModel("Danish (Danish)", R.drawable.denmark, "da", "da-DK"))
        arrayList.add(CountryModel("Dutch (Nederlands)", R.drawable.belgium, "nl", "nl-BE"))
        arrayList.add(CountryModel("Esperanto (Esperanto)", R.drawable.united_states_of_america, "eo", "eo-DZ"))
        arrayList.add(CountryModel("Estonian (Estonian)", R.drawable.estonia, "et", "et-EE"))
        arrayList.add(CountryModel("Filipino (Pilipino)", R.drawable.philippines, "fil", "fil-PH"))
        arrayList.add(CountryModel("Finnish (Finnish)", R.drawable.finland, "fi", "fi-FI"))
        arrayList.add(CountryModel("French (français)", R.drawable.france, "fr", "fr-FR"))
        arrayList.add(CountryModel("Frisian (Frisian)", R.drawable.germany, "fy", "fy-DEU"))
        arrayList.add(CountryModel("Galician (Galician)", R.drawable.spain, "gl", "gl-ES"))
        arrayList.add(CountryModel("Georgian (ქართული)", R.drawable.georgia, "ka", "ka-GE"))
        arrayList.add(CountryModel("German (Deutsch)", R.drawable.germany, "de", "de-DE"))
        arrayList.add(CountryModel("Greek (Ελληνικά)", R.drawable.greece, "el", "el-GR"))
        arrayList.add(CountryModel("Gujarati (ગુજરાતી)", R.drawable.india, "gu", "gu-IN"))
        arrayList.add(CountryModel("Haitian (Ayisyen)", R.drawable.haiti, "ht", "ht-HTI"))
        arrayList.add(CountryModel("Hausa (Hausa)", R.drawable.hawaii, "ha", "ha-HUA"))
        arrayList.add(CountryModel("Hawaiian (Ōlelo Hawaiʻi)", R.drawable.united_states_of_america, "haw", "haw-US"))
        arrayList.add(CountryModel("Hindi (हिंदी)", R.drawable.india, "hi", "hi-IN"))
        arrayList.add(CountryModel("Hmong (Hmoob)", R.drawable.china, "hmn", "hmn-Hm"))
        arrayList.add(CountryModel("Hungarian (Magyar)", R.drawable.hungary, "hu", "hu-HU"))
        arrayList.add(CountryModel("Icelandic (izlandi)", R.drawable.iceland, "is", "is-IS"))
        arrayList.add(CountryModel("Indonesian (Indonesian)", R.drawable.indonesia, "id", "id-ID"))
        arrayList.add(CountryModel("Italian (Italiano)", R.drawable.italy, "it", "it-IT"))
        arrayList.add(CountryModel("Japanese (日本語)", R.drawable.japan, "ja", "ja-JP"))
        arrayList.add(CountryModel("Javanese (Basa jawa)", R.drawable.indonesia, "jv", "jv-ID"))
        arrayList.add(CountryModel("Kannada (ಕನ್ನಡ)", R.drawable.ic_hindi, "kn", "kn-IN"))
        arrayList.add(CountryModel("Khmer (ភាសាខ្មែរ)", R.drawable.combodia_flag, "km", "km-IN"))
        arrayList.add(CountryModel("Korean (한국어)", R.drawable.south_korea, "ko", "ko-KR"))
        arrayList.add(CountryModel("Kurdish (Kurdî)", R.drawable.iran, "ku", "ku-KUR"))
        arrayList.add(CountryModel("Kyrgyz (Кыргызча)", R.drawable.kyrgyzstan, "ky", "ky-KGZ"))
        arrayList.add(CountryModel("Lao (ລາວ)", R.drawable.laos, "lo", "lo-LA"))
        arrayList.add(CountryModel("Latvian (Latviešu valoda)", R.drawable.latvia, "lv", "lv-LV"))
        arrayList.add(CountryModel("Lithuanian (Lietuvių)", R.drawable.lithuania, "lt", "lt-LT"))
        arrayList.add(CountryModel("Macedonian (Македонски)", R.drawable.republic_of_macedonia, "mk", "mk-MK"))
        arrayList.add(CountryModel("Malagasy (Малгашки)", R.drawable.united_states_of_america, "mg", "mg-MGD"))
        arrayList.add(CountryModel("Malay (Bahasa Melayu)", R.drawable.malaysia, "ms", "ms-MY"))
        arrayList.add(CountryModel("Malayalam (മലയാളം)", R.drawable.india, "ml", "ml-IN"))
        arrayList.add(CountryModel("Maltese (Malti)", R.drawable.malta, "mt", "mt-MLT"))
        arrayList.add(CountryModel("Maori (Maori)", R.drawable.united_states_of_america, "mi", "mi-MIO"))
        arrayList.add(CountryModel("Marathi (मराठी)", R.drawable.india, "mr", "mr-IN"))
        arrayList.add(CountryModel("Mongolian (Монгол хэл дээр)", R.drawable.mongolia, "mn", "mn-MN"))
        arrayList.add(CountryModel("Myanmar (Myanmar)", R.drawable.myanmar, "my", "my-MMR"))
        arrayList.add(CountryModel("Nepali (नेपाली)", R.drawable.nepal, "ne", "ne-NP"))
        arrayList.add(CountryModel("Norwegian (norsk)", R.drawable.norway, "no", "no-NO"))
        arrayList.add(CountryModel("Pashto (پښتو)", R.drawable.pakistan, "ps", "ps-PK"))
        arrayList.add(CountryModel("Persian (فارسي)", R.drawable.iran, "fa", "fa-FA"))
        arrayList.add(CountryModel("Polish (Polskie)", R.drawable.poland, "pl", "pl-PL"))
        arrayList.add(CountryModel("Portuguese (Português)", R.drawable.portuguese, "pt", "pt-BR"))
        arrayList.add(CountryModel("Punjabi (ਪੰਜਾਬੀ)", R.drawable.india, "pa", "pa-IN"))
        arrayList.add(CountryModel("Romanian (Română)", R.drawable.romania, "ro", "ro-RO"))
        arrayList.add(CountryModel("Russian (русский)", R.drawable.russia, "ru", "ru-RU"))
        arrayList.add(CountryModel("Samoan (Samoa)", R.drawable.samoa, "sm", "sm-WSM"))
        arrayList.add(CountryModel("Scots (Scots)", R.drawable.scotland, "gd", "gd-GBR"))
        arrayList.add(CountryModel("Serbian (Српски)", R.drawable.serbia, "sr", "sr-RS"))
        arrayList.add(CountryModel("Shona (Shona)", R.drawable.zimbabwe, "sn", "sn-SNA"))
        arrayList.add(CountryModel("Sindhi (سنڌي)", R.drawable.pakistan, "sd", "sd-Pk"))
        arrayList.add(CountryModel("Sinhala (සිංහල)", R.drawable.sri_lanka, "si", "si-LK"))
        arrayList.add(CountryModel("Slovak (slovenský)", R.drawable.slovakia, "sk", "sk-SK"))
        arrayList.add(CountryModel("Slovenian (Slovenščina)", R.drawable.slovenia, "sl", "sl-SI"))
        arrayList.add(CountryModel("Somali (Somali)", R.drawable.somalia, "so-SOM", "so-SOM"))
        arrayList.add(CountryModel("Spanish (Español)", R.drawable.spanish_flag, "es", "es-US"))
        arrayList.add(CountryModel("Sundanese (Sunda)", R.drawable.sudan, "su", "su-ID"))
        arrayList.add(CountryModel("Swahili (Swahili)", R.drawable.kenya, "sw", "sw-KE"))
        arrayList.add(CountryModel("Swedish (svenska)", R.drawable.sweden, "sv", "sv-SE"))
        arrayList.add(CountryModel("Tagalog (Tagalog)", R.drawable.portugal, "tl", "tl-TGL"))
        arrayList.add(CountryModel("Tajik (Тоҷикӣ)", R.drawable.tajikistan, "tg", "tg-TJK"))
        arrayList.add(CountryModel("Tamil (தமிழ்)", R.drawable.india, "ta", "ta-IN"))
        arrayList.add(CountryModel("Telugu (తెలుగు)", R.drawable.india, "te", "te-IN"))
        arrayList.add(CountryModel("Thai (ไทย)", R.drawable.thailand, "th", "th-TH"))
        arrayList.add(CountryModel("Turkish (Türk)", R.drawable.turkey, "tr", "tr-TR"))
        arrayList.add(CountryModel("Ukrainian (Українська)", R.drawable.ukraine, "uk", "uk-UA"))
        arrayList.add(CountryModel("Urdu (اردو)", R.drawable.pakistan, "ur", "ur-PK"))
        arrayList.add(CountryModel("Uzbek (O zbek)", R.drawable.uzbekistn, "uz", "uz-UZ"))
        arrayList.add(CountryModel("Vietnamese (Tiếng Việt)", R.drawable.vietnam, "vi", "vi-VN"))
        arrayList.add(CountryModel("Welsh (Welsh)", R.drawable.wales, "cy", "cy-GBR"))
        arrayList.add(CountryModel("Xhosa (Xhosa)", R.drawable.south_africa, "xh", "xh-XHO"))
        arrayList.add(CountryModel("Zulu (IsiZulu)", R.drawable.south_africa, "zu", "zu-ZA"))
        return arrayList
    }
}