package com.qrcodescanner.barcodereader.qrgenerator.utils

import com.qrcodescanner.barcodereader.qrgenerator.R
import com.qrcodescanner.barcodereader.qrgenerator.models.AllCountryModel


object CountryList {
    fun getCountryListDup(): ArrayList<AllCountryModel> {
        val arrayList = ArrayList<AllCountryModel>()
        arrayList.add(AllCountryModel("Afrikaans", R.drawable.south_africa, "af", "af-ZA"))
        arrayList.add(AllCountryModel("Albanian", R.drawable.albania, "sq", "sq-AL"))
        arrayList.add(AllCountryModel("Arabic", R.drawable.ic_saudi_arabia, "ar", "ar-SA"))
        arrayList.add(AllCountryModel("Belarusian", R.drawable.ic_belaruse, "be", "be-BY"))
        arrayList.add(AllCountryModel("Bulgarian", R.drawable.bulgaria, "bg", "bg-BG"))
        arrayList.add(AllCountryModel("Bengali", R.drawable.bangladesh, "bn", "bn-BD"))
        arrayList.add(AllCountryModel("Catalan", R.drawable.catalon, "ca", "ca-ES"))
        arrayList.add(AllCountryModel("Chinese", R.drawable.china, "zh", "zh-CN"))
        arrayList.add(AllCountryModel("Croatian", R.drawable.croatia, "hr", "hr-HR"))
        arrayList.add(AllCountryModel("Czech", R.drawable.czech_republic, "cs", "cs-CZ"))
        arrayList.add(AllCountryModel("Danish", R.drawable.denmark, "da", "da-DK"))
        arrayList.add(AllCountryModel("Dutch", R.drawable.belgium, "nl", "nl-BE"))
        arrayList.add(AllCountryModel("English", R.drawable.united_states_of_america, "en", "en-US"))
        arrayList.add(AllCountryModel("Esperanto", R.drawable.united_states_of_america, "eo", "eo-DZ"))
        arrayList.add(AllCountryModel("Estonian", R.drawable.estonia, "et", "et-EE"))
        arrayList.add(AllCountryModel("Finnish", R.drawable.finland, "fi", "fi-FI"))
        arrayList.add(AllCountryModel("French", R.drawable.france, "fr", "fr-FR"))
        arrayList.add(AllCountryModel("Galician", R.drawable.spain, "gl", "gl-ES"))
        arrayList.add(AllCountryModel("Georgian", R.drawable.georgia, "ka", "ka-GE"))
        arrayList.add(AllCountryModel("German", R.drawable.germany, "de", "de-DE"))
        arrayList.add(AllCountryModel("Greek", R.drawable.greece, "el", "el-GR"))
        arrayList.add(AllCountryModel("Gujarati", R.drawable.india, "gu", "gu-IN"))
        arrayList.add(AllCountryModel("Haitian Creole", R.drawable.haiti, "ht", "ht-HTI"))
        arrayList.add(AllCountryModel("Hebrew", R.drawable.ic_isreal, "he", "he-IL"))
        arrayList.add(AllCountryModel("Hindi", R.drawable.india, "hi", "hi-IN"))
        arrayList.add(AllCountryModel("Hungarian", R.drawable.hungary, "hu", "hu-HU"))
        arrayList.add(AllCountryModel("Icelandic", R.drawable.iceland, "is", "is-IS"))
        arrayList.add(AllCountryModel("Indonesian", R.drawable.indonesia, "id", "id-ID"))
        arrayList.add(AllCountryModel("Irish", R.drawable.ic_irland, "ga", "ga-IE"))
        arrayList.add(AllCountryModel("Italian", R.drawable.italy, "it", "it-IT"))
        arrayList.add(AllCountryModel("Japanese", R.drawable.japan, "ja", "ja-JP"))
        arrayList.add(AllCountryModel("Kannada", R.drawable.india, "kn", "kn-IN"))
        arrayList.add(AllCountryModel("Korean", R.drawable.south_korea, "ko", "ko-KR"))
        arrayList.add(AllCountryModel("Lithuanian", R.drawable.lithuania, "lt", "lt-LT"))
        arrayList.add(AllCountryModel("Latvian", R.drawable.latvia, "lv", "lv-LV"))
        arrayList.add(AllCountryModel("Macedonian", R.drawable.republic_of_macedonia, "mk", "mk-MK"))
        arrayList.add(AllCountryModel("Marathi", R.drawable.india, "mr", "mr-IN"))
        arrayList.add(AllCountryModel("Malay", R.drawable.malaysia, "ms", "ms-MY"))
        arrayList.add(AllCountryModel("Maltese", R.drawable.malta, "mt", "mt-MLT"))
        arrayList.add(AllCountryModel("Norwegian", R.drawable.norway, "no", "no-NO"))
        arrayList.add(AllCountryModel("Persian", R.drawable.iran, "fa", "fa-FA"))
        arrayList.add(AllCountryModel("Polish", R.drawable.poland, "pl", "pl-PL"))
        arrayList.add(AllCountryModel("Portuguese", R.drawable.portuguese, "pt", "pt-BR"))
        arrayList.add(AllCountryModel("Romanian", R.drawable.romania, "ro", "ro-RO"))
        arrayList.add(AllCountryModel("Russian", R.drawable.russia, "ru", "ru-RU"))
        arrayList.add(AllCountryModel("Slovak", R.drawable.slovakia, "sk", "sk-SK"))
        arrayList.add(AllCountryModel("Slovenian", R.drawable.slovenia, "sl", "sl-SI"))
        arrayList.add(AllCountryModel("Spanish", R.drawable.spanish_flag, "es", "es-US"))
        arrayList.add(AllCountryModel("Swedish", R.drawable.sweden, "sv", "sv-SE"))
        arrayList.add(AllCountryModel("Swahili", R.drawable.south_africa, "sw", "sw-SW"))
        arrayList.add(AllCountryModel("Tagalog", R.drawable.philippines, "tl", "tl-PH"))
        arrayList.add(AllCountryModel("Tamil", R.drawable.india, "ta", "ta-IN"))
        arrayList.add(AllCountryModel("Telugu", R.drawable.india, "te", "te-IN"))
        arrayList.add(AllCountryModel("Thai", R.drawable.thailand, "th", "th-TH"))
        arrayList.add(AllCountryModel("Turkish", R.drawable.turkey, "tr", "tr-TR"))
        arrayList.add(AllCountryModel("Ukrainian", R.drawable.ukraine, "uk", "uk-UA"))
        arrayList.add(AllCountryModel("Urdu", R.drawable.pakistan, "ur", "ur-PK"))
        arrayList.add(AllCountryModel("Vietnamese", R.drawable.vietnam, "vi", "vi-VN"))
        arrayList.add(AllCountryModel("Welsh", R.drawable.wales, "cy", "cy-GB"))
        return arrayList
    }
}
