package com.qrcodescanner.barcodereader.qrgenerator.utils

object RemoteConfigKeys {

    //soT_ Adlib
    const val BANNER_SPLASH = "BANNER_SPLASH"
    const val RESUME_INTER_SPLASH = "RESUME_INTER_SPLASH"
    const val NATIVE_LANGUAGE_1 = "NATIVE_LANGUAGE_1"
    const val NATIVE_LANGUAGE_2 = "NATIVE_LANGUAGE_2"
    const val NATIVE_SURVEY_1 = "NATIVE_SURVEY_1"
    const val NATIVE_SURVEY_2 = "NATIVE_SURVEY_2"
    const val NATIVE_WALKTHROUGH_1 = "NATIVE_WALKTHROUGH_1"
    const val NATIVE_WALKTHROUGH_2 = "NATIVE_WALKTHROUGH_2"
    const val NATIVE_WALKTHROUGH_FULLSCR = "NATIVE_WALKTHROUGH_FULLSCR"
    const val NATIVE_WALKTHROUGH_FULLSCR_NEW = "NATIVE_WALKTHROUGH_FULLSCR_NEW"
    const val NATIVE_WALKTHROUGH_3 = "NATIVE_WALKTHROUGH_3"
    const val INTERSTITIAL_LETS_START = "INTERSTITIAL_LETS_START"
    const val IN_APP_PURCHASES = "IN_APP_PURCHASES"
    const val IS_PURCHASED = "IS_PURCHASED"
    const val OPEN_AD_ENABLE_KEYBOARD = "OPEN_AD_ENABLE_KEYBOARD"
    const val OPEN_AD_INSIDE_APP = "OPEN_AD_INSIDE_APP"
    const val RESUME_OVERALL = "RESUME_OVERALL"
    const val AD_ID_RESUME_OVERALL = "AD_ID_RESUME_OVERALL"
    const val AD_ID_NATIVE_CASTING_CONNECT = "AD_ID_NATIVE_CASTING_CONNECT"
    const val OVERALL_BANNER_RELOADING = "OVERALL_BANNER_RELOADING"

    const val AD_ID_SPLASH_INTERSTITIAL = "AD_ID_SPLASH_INTERSTITIAL"
    const val AD_ID_SPLASH_RESUME = "AD_ID_SPLASH_RESUME"
    const val AD_ID_BANNER_SPLASH = "AD_ID_BANNER_SPLASH"
    const val AD_ID_NATIVE_LANGUAGE_1 = "AD_ID_NATIVE_LANGUAGE_1"
    const val AD_ID_NATIVE_LANGUAGE_2 = "AD_ID_NATIVE_LANGUAGE_2"
    const val AD_ID_NATIVE_SURVEY_1 = "AD_ID_NATIVE_SURVEY_1"
    const val AD_ID_INTERSTITIAL_LETS_START = "AD_ID_INTERSTITIAL_LETS_START"
    const val AD_ID_NATIVE_SURVEY_2 = "AD_ID_NATIVE_SURVEY_2"
    const val AD_ID_NATIVE_WALKTHROUGH_1 = "AD_ID_NATIVE_WALKTHROUGH_1"
    const val AD_ID_NATIVE_WALKTHROUGH_2 = "AD_ID_NATIVE_WALKTHROUGH_2"
    const val AD_ID_NATIVE_WALKTHROUGH_FULLSCR = "AD_ID_NATIVE_WALKTHROUGH_FULLSCR"
    const val AD_ID_NATIVE_WALKTHROUGH_3 = "AD_ID_NATIVE_WALKTHROUGH_3"
    const val INTER_ADDED_REMOTE = "INTER_ADDED_REMOTE"
    const val BANNER_HOME = "BANNER_HOME"
    const val AD_ID_BANNER_HOME = "AD_ID_BANNER_HOME"
    const val INTER_TV_BRAND = "INTER_TV_BRAND"
    const val INTER_CASTING_CONNECT = "INTER_CASTING_CONNECT"
    const val INTER_SAVE_REMOTE = "INTER_SAVE_REMOTE"


    const val RESUME_INSIDE_APP = "RESUME_INSIDE_APP"

    const val RESUME_INTER_SPLASH_MED = "RESUME_INTER_SPLASH_MED"
    const val RESUME_OVERALL_MED = "RESUME_OVERALL_MED"
    const val BANNER_SPLASH_MED = "BANNER_SPLASH_MED"
    const val NATIVE_LANGUAGE_1_MED = "NATIVE_LANGUAGE_1_MED"
    const val NATIVE_LANGUAGE_2_MED = "NATIVE_LANGUAGE_2_MED"
    const val NATIVE_SURVEY_1_MED = "NATIVE_SURVEY_1_MED"
    const val NATIVE_SURVEY_2_MED = "NATIVE_SURVEY_2_MED"
    const val NATIVE_WALKTHROUGH_1_MED = "NATIVE_WALKTHROUGH_1_MED"
    const val NATIVE_WALKTHROUGH_2_MED = "NATIVE_WALKTHROUGH_2_MED"
    const val NATIVE_WALKTHROUGH_FULLSCR_MED = "NATIVE_WALKTHROUGH_FULLSCR_MED"
    const val NATIVE_WALKTHROUGH_FULLSCR_MED_NEW = "NATIVE_WALKTHROUGH_FULLSCR_MED_NEW"
    const val NATIVE_WALKTHROUGH_3_MED = "NATIVE_WALKTHROUGH_3_MED"
    const val INTERSTITIAL_LETS_START_MED = "INTERSTITIAL_LETS_START_MED"

    const val BANNER_BOTTOM_HOME = "BANNER_BOTTOM_HOME"
    const val BANNER_BOTTOM_BRANDS = "BANNER_BOTTOM_BRANDS"
    const val BANNER_BOTTOM_DISCOVER_TV = "BANNER_BOTTOM_DISCOVER_TV"
    const val BANNER_BOTTOM_ADD_REMOTE = "BANNER_BOTTOM_ADD_REMOTE"
    const val BANNER_BOTTOM_REMOTES = "BANNER_BOTTOM_REMOTES"
    const val BANNER_BOTTOM_REMOTE = "BANNER_BOTTOM_REMOTE"
    const val BANNER_BOTTOM_CHANNELS = "BANNER_BOTTOM_CHANNELS"
    const val BANNER_BOTTOM_WEBCASTING = "BANNER_BOTTOM_WEBCASTING"
    const val BANNER_BOTTOM_SETTINGS = "BANNER_BOTTOM_SETTINGS"
    const val BANNER_BOTTOM_CASTING_INSTRUCTIONS="BANNER_BOTTOM_CASTING_INSTRUCTIONS"

    const val NATIVE_BOTTOM_HOME = "NATIVE_BOTTOM_HOME"
    const val NATIVE_DISCOVER = "NATIVE_DISCOVER"
    const val NATIVE_WEBCASTING = "NATIVE_WEBCASTING"
    const val NATIVE_REMOTE_INSTRUCTIONS = "NATIVE_REMOTE_INSTRUCTIONS"

    // Add as needed
    const val INTERSTITIAL_ENTER_CAST = "INTERSTITIAL_ENTER_CAST"
    const val INTERSTITIAL_ENTER_SETTINGS="INTERSTITIAL_ENTER_SETTINGS"
    const val INTERSTITIAL_ADD_REMOTE="INTERSTITIAL_ADD_REMOTE"
    const val INTERSTITIAL_ENTER_REMOTE="INTERSTITIAL_ENTER_REMOTE"

    const val OVERALL_NATIVE_RELOADING = "OVERALL_NATIVE_RELOADING"
    const val TIMER_NATIVE_F_SRC = "TIMER_NATIVE_F_SRC"

    const val AD_ID_NATIVE_TAP_START = "AD_ID_NATIVE_TAP_START"
    const val NATIVE_TAP_START = "NATIVE_TAP_START"

    const val BANNER_ADD_REMOTE = "BANNER_ADD_REMOTE"
    const val AD_ID_BANNER_ADD_REMOTE = "AD_ID_BANNER_ADD_REMOTE"

    const val BANNER_REMOTE_ADDED = "BANNER_REMOTE_ADDED"
    const val AD_ID_BANNER_REMOTE_ADDED = "AD_ID_BANNER_REMOTE_ADDED"

    const val INTER_ADD_REMOTE = "INTER_ADD_REMOTE"
    const val AD_ID_INTER_ADD_REMOTE = "AD_ID_INTER_ADD_REMOTE"

    const val AD_ID_INTER_INSIDE = "AD_ID_INTER_INSIDE"

    const val NATIVE_DISCOVER_TV = "NATIVE_DISCOVER_TV"
    const val AD_ID_NATIVE_DISCOVER_TV = "AD_ID_NATIVE_DISCOVER_TV"

    const val BANNER_DISCOVER_TV = "BANNER_DISCOVER_TV"
    const val AD_ID_BANNER_DISCOVER_TV = "AD_ID_BANNER_DISCOVER_TV"

    const val BANNER_MUSIC_LIST = "BANNER_MUSIC_LIST"
    const val AD_ID_BANNER_MUSIC_LIST = "AD_ID_BANNER_MUSIC_LIST"

    const val BANNER_VIDEO_GALLARY = "BANNER_VIDEO_GALLARY"
    const val AD_ID_BANNER_VIDEO_GALLARY = "AD_ID_BANNER_VIDEO_GALLARY"

    const val BANNER_PHOTO_GALLARY = "BANNER_PHOTO_GALLARY"
    const val AD_ID_BANNER_PHOTO_GALLARY = "AD_ID_BANNER_PHOTO_GALLARY"

    const val INTER_CASTING_ENTER = "INTER_CASTING_ENTER"
    const val INTER_CHANNEL_ENTER = "INTER_CHANNEL_ENTER"

    const val NATIVE_CASTING_CONNECT = "NATIVE_CASTING_CONNECT"
    const val NATIVEAD_ID_NATIVE_CASTING_CONNECT = "NATIVEAD_ID_NATIVE_CASTING_CONNECT"

    const val NATIVE_IMAGE_PREVIEW = "NATIVE_IMAGE_PREVIEW"
    const val AD_ID_NATIVE_IMAGE_PREVIEW = "AD_ID_NATIVE_IMAGE_PREVIEW"

    const val NATIVE_VIDEO_AUDIO_CONTROL = "NATIVE_VIDEO_AUDIO_CONTROL"
    const val AD_ID_NATIVE_VIDEO_AUDIO_CONTROL = "AD_ID_NATIVE_VIDEO_AUDIO_CONTROL"

    const val INTER_SETTINGS_ENTER = "INTER_SETTINGS_ENTER"

    const val INTER_CASTING_DISCONNECT = "INTER_CASTING_DISCONNECT"

}